-- Sample SQL Script for Oracle Database

-- Create a sample table
CREATE TABLE employees (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    email VARCHAR2(100) UNIQUE,
    hire_date DATE DEFAULT SYSDATE,
    job_id VARCHAR2(10),
    salary NUMBER(8, 2),
    department_id NUMBER,
    CONSTRAINT pk_employees PRIMARY KEY (employee_id)
);

-- Insert sample data into the table
INSERT INTO employees (first_name, last_name, email, job_id, salary, department_id) VALUES ('John', 'Doe', 'john.doe@example.com', 'IT_PROG', 60000, 10);
INSERT INTO employees (first_name, last_name, email, job_id, salary, department_id) VALUES ('Jane', 'Smith', 'jane.smith@example.com', 'HR_REP', 55000, 20);
INSERT INTO employees (first_name, last_name, email, job_id, salary, department_id) VALUES ('Robert', 'Brown', 'robert.brown@example.com', 'SA_REP', 50000, 30);

-- Commit the changes
COMMIT;

-- Query to retrieve all employees
SELECT * FROM employees;

-- Update an employee's salary
UPDATE employees SET salary = salary * 1.1 WHERE job_id = 'IT_PROG';

-- Delete an employee
DELETE FROM employees WHERE email = 'john.doe@example.com';

-- Commit the changes
COMMIT;